### ISSUE TITLE
Rotation direction

### ISSUE THREAD

**Issue by lucach** [LuCEresearchlab/pytamaro#11]
Directions of rotation (of the `rotate` function, of the `circular_sector` function and of the new `triangle` function) do not match and this needs to be fixed.
Both Haskell's diagrams and Racket's image teachpack rotate counterclockwise by default. Matthias' JTamaro rotates clockwise. 

@hauswirth is there a rationale for your choice?

**Comment by hauswirth** [comment]
IMO, the key is that all contexts in which we use angles are consistent (either all use CW for positive angles, or all use CCW for positive angles). The math high school script I have uses CCW for positive angles, so that's consistent with Haskell's diagrams and Racket's image teachpack. We should go with that.

**Comment by lucach** [comment]
Agreed. I've changed `circular_sector` in PyTamaro and kept the rotation and the triangle counterclockwise.

You might want to [adapt JTamaro here](https://github.com/LuCEresearchlab/jtamaro/blob/aa15002e30c2e00ec1c6c65c06361795e6e4e739/src/jtamaro/internal/representation/RotateImpl.java#L19).
