### ISSUE TITLE
Connections with Designer

### ISSUE THREAD

**Issue by acbart** [LuCEresearchlab/pytamaro#2]
Hello! I just wanted to say hello from the Designer project. It seems like we have somewhat similar goals and projects, albeit with very different approaches and focuses. I don't really have any specific proposals, but at least being aware of each other and learning what we can seems useful. I love what you're doing with PyTamaro, and can't wait to see more about it!

You may have already seen Designer, but [this page](https://designer-edu.github.io/research/) has more information about research, and this page has more [docs and examples on the library](https://designer-edu.github.io/designer/).

**Comment by lucach** [comment]
Hi @acbart,

Apologies for not following up here! Despite the embarrassing lack of communication, we did not forget about Designer while [writing this paper on comparing PyTamaro with other graphics library for education](https://www.chiodini.org/publications/splashe23-pytamaro.pdf).

I've noticed we're both attending SIGCSE next week: it might be a nice opportunity to meet and talk about interesting stuff going on for both of us (on programming with graphics or otherwise!). See you there!
