### ISSUE TITLE
Antialiasing in output

### ISSUE THREAD

**Issue by redelmann** [LuCEresearchlab/pytamaro#29]
Currently, when converting the graphic to a bitmap image the result is not anti-aliased.

Moreover, applying anti-aliasing techniques manually is rather difficult.
For instance, to apply supersampling, one could create a scaled-up version of the graphic, and then resize down the Image using Pillow's resize with LANCZOS resampling. Due to the lack of a scaling combinator, this requires tedious manual scaling of all dimensions used in the graphic by the user.

Personally, I would suggest adding either: 
- an antialiasing boolean parameter to the various functions that convert graphic to bitmap (show_graphic, save_graphic, graphic_to_image, graphic_to_pillow_image, ...), maybe leveraging skia ?
- a scale parameter to the same output functions.

**Comment by lucach** [comment]
Hi! Thanks for the suggestion!

> an antialiasing boolean parameter to the various functions that convert graphic to bitmap (show_graphic, save_graphic, graphic_to_image, graphic_to_pillow_image, ...), maybe leveraging skia ?

Skia definitely supports antialiasing (via [SkPaint](https://skia.org/docs/user/api/skpaint_overview/)), we could easily support it in PyTamaro. I wonder why you are suggesting a parameter, instead of enabling it by default (I could think about performance reasons, but that is quite out of scope for our educational context). I'd like to minimize the number of parameters, in general. Do you have an example in mind for which you would want to have it off?

> a scale parameter to the same output functions.

This is deliberately not in PyTamaro because we want to nudge learners to _parameterize_ their own functions and with a scaling function they can avoid doing the work and actually learn ([more on this in this research paper that explains PyTamaro's design](https://www.chiodini.org/publications/splashe23-pytamaro.pdf)).

**Comment by lucach** [comment]
> Do you have an example in mind for which you would want to have it off?

Related and opposite question: which situation/graphic prompted you to need anti-aliasing?

**Comment by redelmann** [comment]
Hi @lucach ! Thank you very much for the quick response!

I am not opposed to having antialiasing on by default, of course.
On the contrary, I think this would be great.

For the context, I was trying PyTamaro for the first time this weekend (after a great presentation last Saturday by @hauswirth) and coded the SBB clock from scratch. Unfortunately, when I displayed the result, the image was not as beautiful as I would have expected. To obtain a crisp output, I had to manually scale all dimensions used by a factor 2 and then resize the image using Pillow. SVG output was also a solution, but is more cumbersome to use.

I have read your awesome paper and I totally understand and fully support the argument not to include scaling as a combinator for the definition of graphics.
I would only suggest that it is added as a parameter to the functions producing the final output.
This way, students (and other users) still need to learn parameterize to their graphics if they need to scale shapes to create their graphic, but can zoom in to see the final result.
Now that I think about it, having this scaling parameter for display could also be helpful for visually impaired students that may need to produce a larger version of their graphic to better see it, without needing to tweak the instructions.

**Comment by lucach** [comment]
After some testing and [some performance improvements](https://github.com/LuCEresearchlab/pytamaro/commit/65ff1481ea63939b5f59a19cf7fe5bffac9429a2), I say we can always enable antialiasing.

Rendering 10K characters with antialiasing takes ~750ms, as opposed to ~530ms without. Given that this is a rather extreme test for our purposes, we can afford to have it always enabled.

Change introduced in cb78384e0c15b6b2298162f62c0112f36abb74db (curiously enough, the change itself is one line, but some of our testing assumptions no longer hold -- due to antialiasing, the rendering of a red ellipse no longer only contains purely red pixels).

Thanks for the suggestion @redelmann , it's something we overlooked so far!

---

> I would only suggest that it is added as a parameter to the functions producing the final output.
This way, students (and other users) still need to learn parameterize to their graphics if they need to scale shapes to create their graphic, but can zoom in to see the final result.

I see, that indeed would not be as problematic as the combinator. But my experience suggests that learners would still exploit it: just last week an otherwise excellent project done by a couple of students still did not have proper parameterization for the graphics. They were rendering cards for the game of UNO, and they couldn't produce bigger renderings of a card because of some hardcoded sizes. I totally feel you for the inconvenience (which can be bypassed with SVG, in any case), but I still maintain that it is a valuable learning opportunity. Not including it, at least for the time being  :-)

**Comment by redelmann** [comment]
Thank you very much for the quick implementation! It's great that anti-aliasing can be always on. Just tested it myself and the rendering is beautiful! Thanks for the great work!
