### ISSUE TITLE
Multi-language standardisation

### ISSUE THREAD

**Issue by frovaaa** [LuCEresearchlab/pytamaro#38]
While doing some experiments on the `AST` form of the library I noticed that the implementation of the various wrappers and re-definitions for the language translations in the `primitives.py`, `color_names.py` etc. are not made in a standard way.
In particular, how we handle the various name clashes when the destination language is the same as the English one, made me notice this issue.

In some cases like in the French translation for the `compose` method we import all the methods from the English operations `from pytamaro import operations` to then call `return operations.compose(graphique_premier_plan, graphique_arriere_plan)` while for all the other methods we import and use them directly
`from pytamaro.operations import (above, beside, graphic_height, overlay, pin, rotate)`.

In other cases like in the German implementation, we create an alias of the English version, yet again in a non-standardised way:
Example of the `de/primitives.py` 

`from pytamaro.primitives import ellipse as ellipse_e`

`return ellipse_e(breite, hoehe, farbe)`

Sometimes we add a `_e` at the end, sometimes we add `english_` at the beginning.

My suggestion to resolve this issue is to choose a standard, for which I propose:
In every "wrapper file" we import from the pytamaro library using aliasing and keeping the reference to the package.
To explain better here is an example applied to the `it/color_names.py` file:

Import statement
`import pytamaro.color_names as _color_names_en`

Usage
`nero: Colore = _color_names_en.black`

The standard would be to import as an alias the needed "class/package" which will assume the name: `_name_of_package_en`
Then we would use it as
`_name_of_package_en.name_of_method()` or `_name_of_package_en.name_of_constant`

This way we will always be able to use the original English name, without worrying about any name clash in the various languages.

Another issue that gets solved with this implementation is that:
You can access the various operations/names/etc. of the standard English version from any language.

Example:
<img width="990" alt="Screenshot 2024-08-16 at 21 41 04" src="https://github.com/user-attachments/assets/67f01064-7fb9-439a-892d-dc0dac05e479">

By importing the various methods and names directly from the original pytamaro package Python automatically makes them "exported" so they are accessible from outside.

By giving them the "more obfuscated name" we reduce the possibility of them being used when not intended, as they will less likely get suggested by the various auto-completition systems and it would make them less common to wrongly import by using the English name by accident.
It will still be possible to use them, but they would need to import and use the full name `_name_of_package_en.method()`.

A "dirty" solution to completely remove the access to these "side-effect imports", that only work in the name redefinition files like `color_names.py` is to add at the end of the file
`_color_names_en = None`
or use directly the keyword `del`
which will make it impossible to import even through `_color_names_en.nameOfColor`

@lucach thoughts?

**Comment by lucach** [comment]
Good points. Parts of those files have been written by different people, and we never really paid attention to this consistency as we should have. The suggested changes look good, thanks!

Just minor nitpicking: I changed `_en` to `_pytamaro`, so that the import statement reads as more sensible `import pytamaro as _pytamaro`. I also removed the no longer necessary `# pylint: disable=self-assigning-variable` comments, which were exactly an indication of handling this in a suboptimal way.

I've also added a CHANGELOG entry, because the removal of the English names from the language-specific modules is a public-facing change.

> A "dirty" solution to completely remove the access to these "side-effect imports", that only work in the name redefinition files like color_names.py is to add at the end of the file
_color_names_en = None
or use directly the keyword del
which will make it impossible to import even through _color_names_en.nameOfColor

This is not really needed and against the spirit of Python. Using an underscore-prefixed name already hides them when using `import *`.
